name: Build Raspberry Pi Kernel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build Kernel
      run: |
        cd Code/patch/cm4/20230630
        chmod +x run.sh
        ./run.sh

    - name: Copy and Zip Output
      run: |
        mkdir $HOME/kernel_output
        sudo cp -R Code/patch/cm4/20230630/out/* $HOME/kernel_output/
        cd $HOME/kernel_output
        zip -r kernel-output.zip .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ runner.temp }}/kernel_output/kernel-output.zip
        asset_name: kernel-output.zip
        asset_content_type: application/zip

    - name: Debug - List files
      if: failure()
      run: |
        echo "Home directory contents:"
        ls -R $HOME
        echo "Workspace contents:"
        ls -R ${{ github.workspace }}
        echo "Temp directory contents:"
        ls -R ${{ runner.temp }}
